version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/Le0tk0k/peingo
    steps:
      - checkout
      - run: go build
    deploy:
      machine:
        enabled: true
      steps:
        - run:
          name: deploy via SSH
          command: >
            ssh $SSH_USER@$SSH_HOST "
            cd peingo
            && git pull
            && docker-compose restart
            "
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build